---
- name: Install Apache using Ansible
  hosts: all
  become: false

  tasks:

    - name: Install httpd package
      shell: dnf install -y httpd

    - name: Start httpd service
      shell: systemctl start httpd

    - name: Enable httpd service
      shell: systemctl enable httpd
