---
- name: Simple Ansible POC
  hosts: all
  become: false

  tasks:

    - name: Create a test file
      file:
        path: /tmp/ansible_demo.txt
        state: touch

    - name: Write content to file
      copy:
        content: "Hello from Ansible Automation Platform"
        dest: /tmp/ansible_demo.txt

    - name: Display message
      debug:
        msg: "POC executed successfully!"
